development: &default
  adapter: mysql2
  host: localhost
  username: root
  password: "slayer"
  pool: 5
  timeout: 5000
  database: furniture_store_development

test:
  <<: *default
  database: furniture_store_test<%= ENV['TEST_ENV_NUMBER'] %>

production: &production
  <<: *default
  username: app
  password: "Splash446"
  adapter: postgresql
  database: furniture_store_production

