development: &default
  adapter: mysql2
  host: localhost
  username: root
  password: "slayer"
  pool: 5
  timeout: 5000
  database: furniture_store_development

test:
  <<: *default
  database: furniture_store_test<%= ENV['TEST_ENV_NUMBER'] %>

production: &production
  <<: *default
  adapter: postgresql
  database: furniture_store_production
  username: <%= File.read(Rails.root.join(*%w(.. .. shared user))) rescue "" %>
  password: <%= File.read(Rails.root.join(*%w(.. .. shared password))) rescue "" %>

